fragment GameData on Game {
  id
  dateTime
  homeTeam {
    id
    name
  }
  awayTeam {
    id
    name
  }
  league {
    id
    name
  }
  isPast
}

fragment LineupData on Game {
  lineups {
    id
    team {
      id
      name
      managers {
        id
        user {
          id
        }
      }
    }
    players {
      id
      position
      battingOrderNumber
      player {
        id
        firstName
        lastName
      }
    }
  }
}