#import "gql/fragments/game.gql"

query GetGamePage(
  $pk: ID!
) {
  gameByPk(pk: $pk) {
    ...GameData
    ...LineupData
    homeTeamTotalRuns
    awayTeamTotalRuns
    homeTeamTotalHits
    awayTeamTotalHits
    homeTeamTotalErrors
    awayTeamTotalErrors
    halfInnings {
      inning
      rbis
      errors
      hits
      homeTeamAtBat
    }
  }
}