#import "gql/fragments/game.gql"

query GetGamePage(
  $id: String!
) {
  gameById(id: $id) {
    ...GameData
    ...LineupData
    homeTeamTotalRuns
    awayTeamTotalRuns
    homeTeamTotalHits
    awayTeamTotalHits
    homeTeamTotalErrors
    awayTeamTotalErrors
    halfInnings {
      inning
      rbis
      errors
      hits
      homeTeamAtBat
    }
  }
  auth {
    id
  }
}