query GetLineupById($id: String!) {
  lineupById(id: $id) {
     team {
      name
    }
    opponent{
      name
    }
    players {
      player {
        id
        lastName
        firstName
      }
    	position
      battingOrderNumber
    }
    game {
      dateTime
    }
  }
}