query GetLineupById($id: String!) {
  lineupById(id: $id) {
     team {
      name
    }
    opponent{
      name
    }
    players {
      player {
        id
        lastName
        firstName
        attributes {
          composure
          endurance
          intellect
          reflexes
          speed
          strength
          willpower
        }
      }
    	position
      battingOrderNumber
    }
    game {
      dateTime
    }
  }
}